[package]
name = "pretty_dns_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.5.0"
tracing = "0.1.29"

pretty_dns_message = { path = "../pretty_dns_message" }
